### ISSUE TITLE
Task Area Sizing

### ISSUE THREAD

**Issue by gautam7-github** [rajveersco/LetsDo#1]
Great Design!
However, the task area is too small and too centered for normal usage!!
and the scrolling doesn't work!
<img width="596" alt="image" src="https://user-images.githubusercontent.com/61959145/159119018-c5a82ea1-1e72-43c1-8ed2-436604118356.png">

**Comment by rajveersco** [comment]
Thanks, brother for your compliment,
Actually, it's only accessible on mobile and desktop, not compatible with tablet resolutions
Scrolling works bro... you have to hover in the desktop interface and hold for 2sec in the mobile interface to hide for a better view of tasks click anywhere.

**Comment by rajveersco** [comment]
Your issue has been resolved! 
Now it's fully responsive across most devices except tablet with resolution <=500

**Comment by gautam7-github** [comment]
Thanks a ton!
